services:
  # Servidor Backend FastAPI (Python + PyTorch + Java/Pellet)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app:z
    environment:
      - PYTHONUNBUFFERED=1

  # Frontend Flutter Web (Servido via Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80" # O frontend estará disponível em http://localhost:8080
    depends_on:
      - api
